# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199D1vl5c7ydxE4XSMWel2nXwr12x5vBD
"""

!python -m spacy download en_core_web_md

import spacy.cli
spacy.cli.download("en_core_web_md")
import en_core_web_md

content = open('movies.txt', 'r')
movies = " "

for line in content:
  movies += line

content.close()
print(movies)

import spacy
nlp = en_core_web_md.load()

film = """Will he save their world or destroy it? When the Hulk becomes too dangerous for the Earth, the Illuminati trick Hulk into a shuttle and 
          launch him into space to a planet where the Hulk can live in peace. Unfortunately, Hulk land on the planet Sakaar where he is sold 
          into slavery and trained as a gladiator."""

films = movies + '\n'
model_film = nlp(film)

for token1 in films:
  token1 = nlp(token1)
  for token2 in model_film:
    print(token1.text, token2.text, token1.similarity(token2))